version: '3.4'

services:
  fotoquestgocommandapi:
    image: ${DOCKER_REGISTRY-}fotoquestgocommandapi
    build:
      context: .
      dockerfile: FotoQuestGoCommandApi/Dockerfile
    depends_on:
      - db
    networks:
      - nat
  fotoquestgoqueryapi:
    image: ${DOCKER_REGISTRY-}fotoquestgoqueryapi
    build:
      context: .
      dockerfile: FotoQuestGoQueryApi/Dockerfile
    depends_on:
      - db
    networks:
      - nat
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
        SA_PASSWORD: "Password123!"
        ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    networks:
      - nat
networks:
  nat:
    driver: bridge

